version: "3.0"
services: 
  qinglong:
    image: whyour/qinglong:latest
    container_name: ql
    hostname: ql
    restart: always 
    ports: 
      - 5700:5700
    volumes:
      - ./ql/config:/ql/config
      - ./ql/log:/ql/log
      - ./ql/db:/ql/db
