version: "3.0"
service:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    hostname: adguard
    restart: always
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    ports:
      - 9427:53/tcp
      - 9427:53/udp
      - 1538:80/tcp
      - 3345:3000/tcp
     # - 67:67/udp 
     # - 68:68/tcp
     # - 68:68/udp
      - 1683:443/tcp
      - 6328:853/tcp
