version: '3.7'
services:
  mtproxy:
    image: telegrammessenger/proxy:latest
    container_name: mtproxy
    restart: always
    environment:
      - SECRET=
    ports:
      - 666:443
    volumes:
      - ./proxy-config:/data
