version: "3.7"
services:
  xray:
    image: teddysun/xray
    restart: always
    container_name: "xray"
    network_mode: host  
    volumes:
      - ./config.json:/etc/xray/config.json
      - /etc/letsencrypt/live/elec.starstar.cf/fullchain.pem:/etc/xray/fullchain.pem
      - /etc/letsencrypt/live/elec.starstar.cf/privkey.pem:/etc/xray/privkey.pem

