version: "2.0"
services:
  jd:
    image: nevinee/jd:v4
    container_name: jd
    restart: always
    tty: true
    network_mode: bridge
    hostname: jd
    volumes:
      - ./config:/jd/config
      - ./log:/jd/log
      - ./own:/jd/own             # own脚本目录，如需使用，建议映射
      #- ./scripts:/jd/scripts    # 如果想要看到lxk0301大佬的js脚本，可以解除本行注释
    ports:
      - 5678:5678
    environment: 
      - ENABLE_TTYD=false             # 是否在启动容器时自动启动网页终端，当ENABLE_WEB_PANEL=true时此项设置才生效
      - ENABLE_WEB_PANEL=true         # 是否在启动容器时自动启动控制面板
      - ENABLE_HANGUP=true            # 是否在启动容器时自动启动挂机程序
