pagermaid:
  image: id77/pagermaid
  restart: always
  cap_drop:
    - ALL
  container_name: 'pagermaid'
  hostname: 'pagermaid'
  volumes:
    - ./config.yml:/var/lib/pagermaid/config.yml
    - ./plugins:/var/lib/pagermaid/plugins    
    - ./pagermaid.session:/var/lib/pagermaid/pagermaid.session
  tty: true
  command:
    - /bin/sh
    - -c
    - |
      nohup redis-server >/dev/null 2>/dev/null &
      python3 -m pagermaid
